version: "3.7"
services:
  api:
    build:
      context: ./api
      target: prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
      - API_PORT
      - ENABLE_CORS
  client:
    build:
      context: ./client
      target: prod
    ports:
      - 80:80
    environment:
      - ENV
